// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $en_layout from "./routes/en/_layout.tsx";
import * as $en_index from "./routes/en/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $showcase_index from "./routes/showcase/index.tsx";
import * as $vi_layout from "./routes/vi/_layout.tsx";
import * as $vi_index from "./routes/vi/index.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/en/_layout.tsx": $en_layout,
    "./routes/en/index.tsx": $en_index,
    "./routes/index.tsx": $index,
    "./routes/showcase/index.tsx": $showcase_index,
    "./routes/vi/_layout.tsx": $vi_layout,
    "./routes/vi/index.tsx": $vi_index,
  },
  islands: {
    "./islands/Navbar.tsx": $Navbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
